
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'startleftANDAN AND ANDOR ANNEE COURANT JOUR_OU_ANNEE MOIS RANGE SPACE\n        mois_annee : mois ANNEE\n        \n        plage : jour_mois AND jour_mois\n        \n        annee_et_annee : annee AND annee\n        \n        courant_de_groupe : COURANT annee_et_annee\n                            | COURANT ANNEE\n                            | COURANT mois_annee\n        \n        groupe_annee : succession_mois ANNEE\n        \n        annee : AN ANNEE\n                    | ANNEE\n        \n        deux_dates_completes : jour_mois_annee AND jour_mois_annee\n        \n        mois : MOIS\n        \n        date_complete : plage ANNEE\n                     | jour_mois ANNEE\n                     | groupe_annee\n                     | courant_de_groupe\n                     | JOUR_OU_ANNEE mois JOUR_OU_ANNEE\n                     | mois_annee\n                     | annee\n                     | range_mois ANNEE\n                     | range_jour ANNEE\n                     | annee_et_annee\n                     | andor_jour_mois\n                     | andor_date_complete\n                     | jour_mois_annee\n                     | deux_dates_completes\n        \n        start : date_complete\n        \n        range_mois : mois RANGE mois\n        \n        range_jour : JOUR_OU_ANNEE RANGE JOUR_OU_ANNEE\n                    | JOUR_OU_ANNEE RANGE JOUR_OU_ANNEE mois\n        \n        jour_mois : JOUR_OU_ANNEE mois\n        \n        andor_date_complete : jour_mois_annee ANDOR jour_mois_annee\n        jour_mois_annee : JOUR_OU_ANNEE mois ANNEE\n        andor_jour_mois : jour_mois ANDOR jour_mois\n                        | jour_mois ANDOR jour_mois ANNEE\n        \n        succession_mois : mois AND mois\n        '
    
_lr_action_items = {'JOUR_OU_ANNEE':([0,22,25,26,27,28,35,36,],[8,-11,45,45,47,49,54,54,]),'COURANT':([0,],[20,]),'AN':([0,20,32,],[21,21,21,]),'ANNEE':([0,3,5,9,12,13,19,20,21,22,27,32,42,44,46,49,50,51,56,58,59,],[4,23,24,29,33,34,37,39,43,-11,48,4,29,-2,57,-28,-27,-35,-30,-29,48,]),'MOIS':([0,8,20,30,31,45,49,54,],[22,22,22,22,22,22,22,22,]),'$end':([1,2,4,6,7,10,11,14,15,16,17,18,22,23,24,29,33,34,37,38,39,40,43,46,47,48,52,53,55,56,57,],[0,-26,-9,-14,-15,-17,-18,-21,-22,-23,-24,-25,-11,-12,-13,-1,-19,-20,-7,-4,-5,-6,-8,-33,-16,-32,-3,-31,-10,-30,-34,]),'AND':([4,5,9,11,17,22,27,39,41,43,48,],[-9,25,31,32,36,-11,-30,-9,32,-8,-32,]),'ANDOR':([5,17,22,27,48,],[26,35,-11,-30,-32,]),'RANGE':([8,9,22,],[28,30,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'date_complete':([0,],[2,]),'plage':([0,],[3,]),'jour_mois':([0,25,26,],[5,44,46,]),'groupe_annee':([0,],[6,]),'courant_de_groupe':([0,],[7,]),'mois':([0,8,20,30,31,45,49,54,],[9,27,42,50,51,56,58,59,]),'mois_annee':([0,20,],[10,40,]),'annee':([0,20,32,],[11,41,52,]),'range_mois':([0,],[12,]),'range_jour':([0,],[13,]),'annee_et_annee':([0,20,],[14,38,]),'andor_jour_mois':([0,],[15,]),'andor_date_complete':([0,],[16,]),'jour_mois_annee':([0,35,36,],[17,53,55,]),'deux_dates_completes':([0,],[18,]),'succession_mois':([0,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('mois_annee -> mois ANNEE','mois_annee',2,'p_mois_annee','parser.py',18),
  ('plage -> jour_mois AND jour_mois','plage',3,'p_plage_dates','parser.py',24),
  ('annee_et_annee -> annee AND annee','annee_et_annee',3,'p_annee_et_annee','parser.py',30),
  ('courant_de_groupe -> COURANT annee_et_annee','courant_de_groupe',2,'p_courant_de_groupe','parser.py',38),
  ('courant_de_groupe -> COURANT ANNEE','courant_de_groupe',2,'p_courant_de_groupe','parser.py',39),
  ('courant_de_groupe -> COURANT mois_annee','courant_de_groupe',2,'p_courant_de_groupe','parser.py',40),
  ('groupe_annee -> succession_mois ANNEE','groupe_annee',2,'p_succession_mois_annees','parser.py',46),
  ('annee -> AN ANNEE','annee',2,'p_annee','parser.py',52),
  ('annee -> ANNEE','annee',1,'p_annee','parser.py',53),
  ('deux_dates_completes -> jour_mois_annee AND jour_mois_annee','deux_dates_completes',3,'p_date_complete_date_complete','parser.py',62),
  ('mois -> MOIS','mois',1,'p_mois','parser.py',69),
  ('date_complete -> plage ANNEE','date_complete',2,'p_date_complete','parser.py',75),
  ('date_complete -> jour_mois ANNEE','date_complete',2,'p_date_complete','parser.py',76),
  ('date_complete -> groupe_annee','date_complete',1,'p_date_complete','parser.py',77),
  ('date_complete -> courant_de_groupe','date_complete',1,'p_date_complete','parser.py',78),
  ('date_complete -> JOUR_OU_ANNEE mois JOUR_OU_ANNEE','date_complete',3,'p_date_complete','parser.py',79),
  ('date_complete -> mois_annee','date_complete',1,'p_date_complete','parser.py',80),
  ('date_complete -> annee','date_complete',1,'p_date_complete','parser.py',81),
  ('date_complete -> range_mois ANNEE','date_complete',2,'p_date_complete','parser.py',82),
  ('date_complete -> range_jour ANNEE','date_complete',2,'p_date_complete','parser.py',83),
  ('date_complete -> annee_et_annee','date_complete',1,'p_date_complete','parser.py',84),
  ('date_complete -> andor_jour_mois','date_complete',1,'p_date_complete','parser.py',85),
  ('date_complete -> andor_date_complete','date_complete',1,'p_date_complete','parser.py',86),
  ('date_complete -> jour_mois_annee','date_complete',1,'p_date_complete','parser.py',87),
  ('date_complete -> deux_dates_completes','date_complete',1,'p_date_complete','parser.py',88),
  ('start -> date_complete','start',1,'p_start','parser.py',99),
  ('range_mois -> mois RANGE mois','range_mois',3,'p_range_mois','parser.py',105),
  ('range_jour -> JOUR_OU_ANNEE RANGE JOUR_OU_ANNEE','range_jour',3,'p_range_jour','parser.py',112),
  ('range_jour -> JOUR_OU_ANNEE RANGE JOUR_OU_ANNEE mois','range_jour',4,'p_range_jour','parser.py',113),
  ('jour_mois -> JOUR_OU_ANNEE mois','jour_mois',2,'p_jour_mois','parser.py',125),
  ('andor_date_complete -> jour_mois_annee ANDOR jour_mois_annee','andor_date_complete',3,'p_andor_date_complete','parser.py',131),
  ('jour_mois_annee -> JOUR_OU_ANNEE mois ANNEE','jour_mois_annee',3,'p_jour_mois_annee','parser.py',137),
  ('andor_jour_mois -> jour_mois ANDOR jour_mois','andor_jour_mois',3,'p_andor_jour_mois','parser.py',142),
  ('andor_jour_mois -> jour_mois ANDOR jour_mois ANNEE','andor_jour_mois',4,'p_andor_jour_mois','parser.py',143),
  ('succession_mois -> mois AND mois','succession_mois',3,'p_succession_mois','parser.py',152),
]
